// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksusbqtxpbtjqptnztjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdXNicXR4cGJ0anFwdG56dGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDcyMTgsImV4cCI6MjA2NDY4MzIxOH0.XzUL-a-lXhBthy8pS99P6tjwJnZYDCtUvB5r1Gk7GfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);